version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2025.02
    resource_class: small
    steps:
      - run: echo "<< pipeline.trigger_parameters.webhook.body >>" | jq

workflows:
  build-workflow:
    jobs:
      - build
